<?php

/**
* Implements hook_theme().
*/
function com_hero_theme($existing, $type, $theme, $path) {
	return [
    	'carousel' => [
			'template' => 'hero.carousel',
			'path' => \Drupal::service('extension.list.module')->getPath('com_hero') . '/templates',
			'variables' => ['items' => NULL, 'meta' => NULL],
		],
    	'video_background' => [
			'template' => 'hero.video',
			'path' => \Drupal::service('extension.list.module')->getPath('com_hero') . '/templates',
			'variables' => ['items' => NULL, 'meta' => NULL],
		],
	];
}